ignore:
  - "**/autoreduce_django"
  - "**/manage.py"
  - "**/autoreduce_db/reduction_viewer/migrations/*.py"
  - "**/autoreduce_db/instrument/migrations/*.py"
  - "**/migrations/*"
  - "**/test/*"
  - "**/tests/*"
