name: Tests
on: [ push ]

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ISISScientificComputing/autoreduce-actions/build@master
        with:
          package_name: autoreduce_db
          run_activemq: false
          migrate_creds: false

      - name: Run unit tests
        run: >-
          pytest autoreduce_db --cov=autoreduce_db --cov-report=xml

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Build package for publishing
        if: ${{ github.ref == 'refs/heads/master' }}
        run: python3 -m pip install wheel && python3 setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  dependency-check:
    name: Dependency-Check
    runs-on: ubuntu-18.04
    container: autoreduction/base
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ job.container.image }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ job.container.image }}-pip-

      - name: Pip install
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

  Inspection:
    name: Code Inspection
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ISISScientificComputing/autoreduce-actions/build@master
        with:
          package_name: autoreduce_db
          run_activemq: false
          migrate_creds: false

      - uses: ISISScientificComputing/autoreduce-actions/code_inspection@master
        with:
          package_name: autoreduce_db


